### PR TITLE
Fix the broken test, and clean up stuffs

### LINKED ISSUE #62: Fix spec
@CAMOBAP795 the latest PR was merged but master spec now failed:

```
  1) Metanorma::Cli::Generator.run with local template success for existing template
     Failure/Error: expect(file_exits?(document, template)).to be_truthy, lambda { template }
       Gemfile
     # ./spec/metanorma/cli/generator_spec.rb:123:in `block in expect_document_to_include_base_templates'
     # ./spec/metanorma/cli/generator_spec.rb:122:in `each'
     # ./spec/metanorma/cli/generator_spec.rb:122:in `expect_document_to_include_base_templates'
     # ./spec/metanorma/cli/generator_spec.rb:79:in `block (4 levels) in <top (required)>'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-command-1.0.3/lib/rspec_command.rb:47:in `block (2 levels) in <module:RSpecCommand>'
     # ./vendor/bundle/ruby/2.5.0/gems/rspec-command-1.0.3/lib/rspec_command.rb:45:in `block in <module:RSpecCommand>'
Finished in 19.54 seconds (files took 0.28555 seconds to load)
30 examples, 1 failure
Failed examples:
rspec ./spec/metanorma/cli/generator_spec.rb:65 # Metanorma::Cli::Generator.run with local template success for existing template
```

### PR DESCRIPTION
**Pull request by abunashir**
* Clean up some of code in the document generator
* Simplify permission checking for template directory
* Download a template first and then use it for local test
* Remove re-redundant test to check if templates are empty

Related #57, Fixes #62

### CODE REVIEW

**Comment by abunashir** [comment]
cc: @CAMOBAP795, @ronaldtse

File: lib/metanorma/cli.rb [hunk 1]
```diff
@@ -71,10 +71,12 @@ def self.templates_path
       Pathname.new(Dir.home).join(".metanorma", "templates")
     end
 
-    def self.templates_path_access
-      dir = templates_path
-      dir = dir.parent while !dir.exist?
-      File.writable? dir
+    def self.writable_template_path?
+      unless templates_path && templates_path.writable?
```
Comment (CAMOBAP795) [inline lib/metanorma/cli.rb]: @abunashir  Are you sure that this will work for non-existing path

Comment (abunashir) [reply lib/metanorma/cli.rb]: Good catch!

File: spec/metanorma/cli/generator_spec.rb [hunk 2]
```diff
@@ -64,39 +69,39 @@
     context "with local template" do
       it "success for existing template" do
         document = "./tmp/my-local-document"
-        template = "./templates"
+        template = [Dir.home, ".metanorma", "templates", "csd"].join("/")
```
Comment (abunashir) [inline spec/metanorma/cli/generator_spec.rb]: This expects the template directory to contain the `CSD` template, which normally should be there since lots of other specs are cloning those templates before this command, but for some super random fact it could be the first specs to run and then it could have failed.

As an alternative to download it upfront (in each time a spec) runs, this might be a good approach to try it out and see if that actually happens.

**Comment by abunashir** [comment]
@ronaldtse: feel free to merge it if you are happy with these changes. cc: @CAMOBAP795

File: spec/metanorma/cli/generator_spec.rb (hunk 2 above)
Comment (CAMOBAP795) [reply spec/metanorma/cli/generator_spec.rb]: Good point
