### PR TITLE
Fix collection option related issue

### LINKED ISSUE #283: `metanorma collection collection.yaml` does not work without explicit options
This refers to a bug in the functionality implemented in https://github.com/metanorma/metanorma-cli/issues/205

Right now,

```sh
bundle exec metanorma collection collection.yml
> No value provided for required options '--output-folder'
```

This is wrong, because the option is already provided in the `collection.yaml` file.
https://github.com/metanorma/bipm-si-brochure/blob/a588390f6d323ae9df8ad119027d440543bf5cd8/collection.yml#L30

Clearly the `metanorma collection` command is not reading the YAML options properly. This needs to be fixed.

See: https://github.com/metanorma/bipm-si-brochure/issues/186#issuecomment-1238945275 on reproducing this problem.

### PR DESCRIPTION
**Pull request by abunashir**
We have recently added support to provide collection options either as a command line arguments or options in collection file. But that is only working on the site interface, and the collection cli still expect the `output-folder` as required option.

This commit changes that, so it's not required anymore and it will try to read the option from the file, and if none of those source has this value, then it will use the source as output directory.

Fixes https://github.com/metanorma/metanorma-cli/issues/283

### CODE REVIEW

File: lib/metanorma/cli/command.rb [hunk 1]
```diff
@@ -59,7 +59,7 @@ def compile(file_name = nil)
 
       desc "collection FILENAME", "Render HTML pages from XML/YAML colection"
       option :format, aliases: "-x", type: :string, desc: "Formats to generate"
-      option :output_folder, aliases: "-w", required: true, desc: "Directory to save compiled files"
+      option :output_folder, aliases: "-w", desc: "Directory to save compiled files"
```
[the remark this answers is not in the document]
Comment (abunashir) [reply lib/metanorma/cli/command.rb:62]: It might be bit tricky to comply here, so making an exception here :)

File: lib/metanorma/cli/collection.rb [hunk 2]
```diff
@@ -26,8 +27,14 @@ def collection_file
         @collection_file ||= Metanorma::Collection.parse(file)
       end
 
+      def verify_required_options_are_present
+        if collection_options[:output_folder].nil?
+          raise ArgumentError.new("Missing a required option '--output-folder'")
```
Comment (ronaldtse) [inline lib/metanorma/cli/collection.rb:32]: We shoud provide a default path for "output folder" just like how `metanorma compile sources/sample.adoc` uses the location of the input file as the output folder:

* `metanorma compile sources/sample.adoc` => `sources/sample.xml` output
* `metanorma collection sources/collection.yaml` => `sources/collection.xml` output

**Review by ronaldtse — DISMISSED** [review]

File: lib/metanorma/cli/collection.rb (hunk 2 above)
Comment (abunashir) [reply lib/metanorma/cli/collection.rb:32]: That's a good point to set the source path as a default output folder 👍🏼 

Actually, after looking into it I came across a bit tricky issue - looks like we are recreating the output folder before we write the outputs, so if we use the `source directory` as the output path then it gets removed (along with the source file) in the recreation phase - [here is the source code](https://github.com/metanorma/metanorma/blob/743fbbc7c382aae4a8cf28da3690fd0260e846c1/lib/metanorma/collection_renderer.rb#L47-L51).

So, what do you guys think about using `...source/output` as a default output directory if nothing was provided?

// @ronaldtse, @opoudjis

Comment (ronaldtse) [reply lib/metanorma/cli/collection.rb]: That code is clearly wrong, we should NOT be removing the output directory in any case.

We want to use the source path as the default output folder.

Comment (abunashir) [reply lib/metanorma/cli/collection.rb]: I'm not sure about the exact reasoning whey we need to remove the output directory before writing the output. @andrew2net, @opoudjis - Do you guys have any idea why we are doing that, do [we still need to keep that logic there](https://github.com/metanorma/metanorma/blob/743fbbc7c382aae4a8cf28da3690fd0260e846c1/lib/metanorma/collection_renderer.rb#L47-L51)?

Comment (opoudjis) [reply lib/metanorma/cli/collection.rb]: I would have done it to ensure that only data from the current run was present in the folder. Arguably that's overly cautious. Maybe. Ok, get rid of it.

Comment (abunashir) [reply lib/metanorma/cli/collection.rb]: Cool, I just created a PR for that - https://github.com/metanorma/metanorma/pull/259, once that's merged and released then we can merge this one. FYI, I will update this PR to use the source folder next :)

**Comment by abunashir** [comment]
I just updated the PR to use the source file's folder as default output location for collection. Once that is merged and released - https://github.com/metanorma/metanorma/pull/259, please feel free to merge this one :)

//cc: @ronaldtse, @opoudjis
